apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-drainer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-drainer
subjects:
  - kind: ServiceAccount
    name: node-drainer
